---
swagger: "2.0"
info:
  description: |
    A Simple adidas product API for the On-Boarding hackathon.
    [On-Boarding trainings](https://tools.adidas-group.com/confluence/display/DSBP/Engineers+On-Boarding+trainings) hackathon

    ## Affordances
    This API affords the following actions:
    - Retrieve the list of products
    - Retrieve a single product
    - Create a product
    - Update an existing product (status...)
    - Retrieve reviews about a product
    - Add a product review
    - Create a user
    - Retrieve user profile
    - Retrieve the user wishlist
    - Add a product into the wishlist
    - Delete a specific product from the wishlist
    - Clear the wishlist
  version: 1.0.0
  title: '[Onboarding] Adidas Wishlist API'
  contact:
    name: Carlos Crespo
    email: carlos.henrique.leonel.crespo@adidas.com
host: design.api.3stripes.io
basePath: /virts/adidas/wishlist-api/1.0.0
schemes:
- https
paths:
  /:
    get:
      summary: API Root
      description: Retrieve the API Root
    x-summary: Wishlist
  /products:
    get:
      summary: List of Products
      description: Retrieve the whole list of products
      security:
      - oauth2:
        - read:products
    post:
      summary: New Product
      description: Create a new product
      security:
      - oauth2:
        - write:products
    x-summary: List of Products
  /products/{product_id}:
    get:
      summary: Get Product
      description: Retrieve product details
      security:
      - oauth2:
        - read:products
    patch:
      summary: Update Product
      description: Update product details
      security:
      - oauth2:
        - write:products
    x-summary: Product
  /products/{product_id}/reviews:
    get:
      summary: List product reviews
      description: Retrieve a list of product reviews
      security:
      - oauth2:
        - read:reviews
    post:
      summary: Create product review
      description: Create a new product review
      security:
      - oauth2:
        - write:reviews
    x-summary: List of Product Reviews
  /products/{product_id}/reviews-stats:
    get:
      summary: List product reviews stats
      description: Retrieve a list of product reviews statistics
      security:
      - oauth2:
        - read:reviews:stats
    x-summary: List of Product Reviews Stats
  /users:
    post:
      summary: New user
      description: Create a new user
      security:
      - oauth2:
        - write:users
    x-summary: Users
  /users/{user_id}:
    get:
      summary: User Profile
      description: Retrieve user profile details
      security:
      - oauth2:
        - read:users
    x-summary: User Profile
  /users/{user_id}/wishlist:
    get:
      summary: User Wishlist
      description: Retrieve user wishlist
      security:
      - oauth2:
        - read:wishlist
    post:
      summary: Add product to the wishlist
      description: Add a product to user wishlist
      security:
      - oauth2:
        - write:wishlist
    delete:
      summary: Clear user wishlist
      description: Clear all the products from user wishlist
      security:
      - oauth2:
        - write:wishlist
    x-summary: User Wishlist
  /users/{user_id}/wishlist/{product_id}:
    delete:
      summary: Delete a product from the wishlist
      description: Delete a product from user wishlist
      security:
      - oauth2:
        - write:wishlist
    x-summary: User Product Wishlist
securityDefinitions:
  oauth2:
    description: |2

      There are three available roles in the application:

        - Anonymous -> can log in, log out, see products, see general ratings from a product.
        - User -> all from Anonymous + following scopes: write:wishlist, read:reviews, write:reviews.
        - Admin -> all from Anonymous + following scopes: write:products, read:reviews, read:reviews:stats, read:users, write:users.
    type: oauth2
    authorizationUrl: https://example/oauth
    flow: implicit
    scopes:
      read:products: read all products
      write:products: modify products
      write:wishlist: modify your wishlist
      read:wishlist: read your wishlist
      read:reviews: read all reviews
      write:reviews: write reviews
      read:reviews:stats: read review statistics
      read:users: read users
      write:users: modify users